// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: helloWorld/helloWorld.proto

package helloWorld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrintHelloClient is the client API for PrintHello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrintHelloClient interface {
	PrintHelloWorld(ctx context.Context, in *ReceiveMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type printHelloClient struct {
	cc grpc.ClientConnInterface
}

func NewPrintHelloClient(cc grpc.ClientConnInterface) PrintHelloClient {
	return &printHelloClient{cc}
}

func (c *printHelloClient) PrintHelloWorld(ctx context.Context, in *ReceiveMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/helloWorld.PrintHello/PrintHelloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrintHelloServer is the server API for PrintHello service.
// All implementations must embed UnimplementedPrintHelloServer
// for forward compatibility
type PrintHelloServer interface {
	PrintHelloWorld(context.Context, *ReceiveMessage) (*ResponseMessage, error)
	mustEmbedUnimplementedPrintHelloServer()
}

// UnimplementedPrintHelloServer must be embedded to have forward compatible implementations.
type UnimplementedPrintHelloServer struct {
}

func (UnimplementedPrintHelloServer) PrintHelloWorld(context.Context, *ReceiveMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintHelloWorld not implemented")
}
func (UnimplementedPrintHelloServer) mustEmbedUnimplementedPrintHelloServer() {}

// UnsafePrintHelloServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrintHelloServer will
// result in compilation errors.
type UnsafePrintHelloServer interface {
	mustEmbedUnimplementedPrintHelloServer()
}

func RegisterPrintHelloServer(s grpc.ServiceRegistrar, srv PrintHelloServer) {
	s.RegisterService(&PrintHello_ServiceDesc, srv)
}

func _PrintHello_PrintHelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrintHelloServer).PrintHelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloWorld.PrintHello/PrintHelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrintHelloServer).PrintHelloWorld(ctx, req.(*ReceiveMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// PrintHello_ServiceDesc is the grpc.ServiceDesc for PrintHello service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrintHello_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloWorld.PrintHello",
	HandlerType: (*PrintHelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrintHelloWorld",
			Handler:    _PrintHello_PrintHelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloWorld/helloWorld.proto",
}
